- .devzone/build/jenkins_build.sh
- .devzone/build/jenkins_postbuild.sh
- nml/version_info.py
nml is so far not published when built from sources and neither are DevZone's nml versions used for building NewGRFs updated  when a new version is pushed.
> Enable builds and publishing with DevZone from git source

- examples/train/example_train.nml
0.3 changed 'shorten_vehicle' to 'length', this was missed in one place in the example train nml.  Now fixed.
> Docs: 0.3 changed 'shorten_vehicle' to 'length' - one place missed

- examples/train/example_train.nml
I missed that 'STORE_TEMP(PALETTE_USE_DEFAULT, 0x100)' should be set for last layer drawn.
> Docs: (fix) register 100 should be set correctly to stop drawing layers

- examples/industry/example_industry.nml
- examples/industry/lang/english.lng
- nml/actions/action0properties.py
- nml/actions/action2production.py
- nml/actions/action2var_variables.py
- nml/ast/produce.py
- nml/expression/__init__.py
- nml/expression/cargo.py
- nml/expression/functioncall.py
- nml/global_constants.py
- nml/parser.py
Currently using peter1138's rebase.
Spec documented in the OpenTTD PR https://github.com/OpenTTD/OpenTTD/pull/6867
Still WIP, known issues:
- won't compile grfs using prod. cb version 0 or 1, e.g. https://github.com/andythenorth/firs
- nml examples incomplete
- new features not fully tested
> Industries: support 16 cargos in / 16 cargos out

- nml/actions/action5.py
The number of GUI sprites has increased since the group liveries addition (OpenTTD/OpenTTD#7108).
> Fix: Update OTTD_GUI sprite count.

- README.md
- nml/version_info.py
Changed VERSION to PILLOW_VERSION,
as it got removed with >=pillow-6.0.0.
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>
> Add compatibility with >=pillow-6.0.0

- examples/roadtype_and_tramtype/example_roadtype_and_tramtype.nml
Unused spritesets due to copy-paste from railtypes example, which uses these sprites as crossing underlays.
The included spritesets in the example now match https://wiki.openttd.org/Frosch/NotRoadTypes#Graphics
> Docs: (fixes #45) remove unused spritesets from roadtype example

- setup.py
Various changes, mostly related to packaging. Now always uses cx_freeze to build executables on Windows, and standard packaging otherwise
Call with `setup.py bdist` to build the package
> Codechange: Rewrite setup.py

- nml/version_info.py
Changed PILLOW_VERSION to PIL.__version__,
as it got removed with >=pillow-7.0.0.
In order not to break compatibility with older versions,
PILLOW_VERSION will be used as a fallback.
Closes: #39
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>
> Fix #39: Add compatibility with >=pillow-7.0.0

- build-dist.bat
- nmlc.spec
- regression/Makefile
- setup.py
cx_Freeze was not working correctly, nml_lz77 lib was built and included but not used.
pyinstaller includes and uses the lib, as long as it's next to `nmlc`, this is enforced in `nmlc.spec`.
`python ./setup.py install` was not really usable on windows, as it copied `nmlc` directly, now setuptools will generate a wrapper executable, as it did before 78cd84c.
The batch file just builds the lib at the right place then creates the standalone exe in `dist`.
> Codechange: use pyinstaller to generate standalone executable (and other mostly windows related changes)

- nml/actions/real_sprite.py
- nml/main.py
- nml/spriteencoder.py
- nml/version_info.py
This simplifies the importing and version detection for Pillow by using the imports recommended by Pillow exclusively without fallbacks: `PIL.Image` (supported since before Pillow 1.0) and `PIL.__version__` (supported since Pillow 3.4).
Changes to the version detection were made in #29 and #54 before, but additional discussion in #54 suggests that the changes are not perfectly aligned with Pillow recommendations yet.
As expectd, the version detection seems to work fine for all versions down to Pillow 3.4.0:
```
(venv)matthijs@grubby:~/docs/src/upstream/nml$ pip freeze|grep Pillow
Pillow==6.2.1
(venv)matthijs@grubby:~/docs/src/upstream/nml$ nmlc --version | grep PIL
PIL: 6.2.1
(venv)matthijs@grubby:~/docs/src/upstream/nml$ pip freeze|grep Pillow
Pillow==5.2.0 …
```
> Simplify pillow imports and version detection

- nml/actions/action14.py
- nml/ast/grf.py
- nml/expression/base_expression.py
Added a `uvalue` attribute to `ConstantNumeric` containing unsigned equivalent of value. Using this attribute it's easy to check coherency of min/max. Also used `uvalue` to ensure the parameter settings are in the uint32 range.
> Fix #57: Check coherency of GRF parameters limits

- README.md
- formatting of table of contents (ToC) failed to make a sublist for two sub-items
- missing links in ToC
- ToC & heading numbering made more consistent with OpenTTD README
- irc link made consistent with OpenTTD README
- Alberth and Rubidium moved to inactive developers 
There are other issues I haven't touched in this PR as they will inevitably require discussion.
- link to known issues is to devzone, not GitHub
- active developers needs updating
> Doc: fix minor issues in README

- .gitignore
- regression/Makefile
I made the Makefile easier to read by spliting the multiline commands and adding comments.
I also added to .gitignore all files generated by regression, the compiled lz77 lib and the files generated by `pip install -e .`
> Minor changes in regression Makefile and .gitignore

- nml/generic.py
`[K` on my screen were annoying so instead of removing them I enabled support for them. As VT100 sequences are now enabled, color codes can be used too so I re-enabled the warning color and I changed it to bright yellow because it seems normal yellow is the default powershell foreground (even if visually it's some pale white). And I added color to error messages (bright red, because red is hard to read on default blue powershell background)
Commits should probably be squashed, but that can happen when merging.
> Fix: enable VT100 sequences on windows

- nml/main.py
- nml/parser.py
- nml/tokens.py
- setup.py
Since merge of #63, parser tables are not regenerated when parser and lexer are modified. This new option works around it without disabling optimisations.
> Add: nmlc option to force regeneration of parser tables

- nml/ast/grf.py
Without this fix, `nmlc -d .\example_train.nml` crashes
> Fix: don't try to debug_print not set optional GRF param number

- nml/actions/action2var_variables.py
Addresses #83 
NML support for https://github.com/OpenTTD/OpenTTD/pull/7409/commits/02b2b7b5b41fd7bcc404774b3d31b67a3f0bc73a
> Add: industry vars 0x70 and 0x71

- nml/global_constants.py
(256 persistent registers, available since OpenTTD 1.9.0)
I have no idea if this is required, but it's listed in https://wiki.openttd.org/NewGRF_Specification_Status#OpenTTD_1.9 and also Eddi advises that compilers should completely implement the spec.
> Change: add TTDPatchFlag 0x80 

- .github/workflows/regression.yml
- .github/workflows/release.yml
- .github/workflows/testing.yml
- nml/version_info.py
Not finished yet
Latest release build example: https://github.com/LordAro/nml/actions/runs/83157723
> Add release workflow

- docs/changelog.txt
This isn't 100%, there may be late additions via #102 and #103.
Known issues:
* would benefit from consolidation, e.g. some of the 'fix' commits are for features only introduced in this release
* capitalisation of first word after ':' is inconsistent
* use of commit prefix is inconsistent, e.g. 'change' commits relate to build environment, don't affect nml end user
* order is currently by prefix, then alphabetical, rather than by related items from the user's point-of-view, maybe that should be changed?
Some of these we should fix, some aren't a big deal for this time :)
`TrueBrain "as it goes: learn from the past, live in the future"`
> Doc: Changelog for 0.5.0 release

- nml/actions/action0.py
According to the NFO spec, there can be up to 63 each of road/tramtypes.
OpenTTD also requires that the *combined* total of road and tram types be
no more than 63, and that a label used for a roadtype cannot be used for
a tramtype or vice versa.
This directly contradicts the NFO specification, and nmlc will not
check for, nor enforce, these additional limitations.
> Fix: Correct limit of available road/tramtypes.

- nml/version_info.py
Previous, and invalid, version format was `<year>-<month>-<day>[-<branch>]-g<changeset>[M]`.
I replaced it with `<next nml version>.dev<year><month><day>+[branch.]g<changeset>[m]`.
For releases it will still use `<tag>[m]`, and a modified tag source will be considered as invalid.
> Fix #100: follow PEP440 when generating version

- .github/workflows/release.yml
- .gitignore
- README.md
Split up the release workflow into separate jobs, as trying to keep them together was just making things difficult to read.
Now builds source tarball with MacOS to get that LF line ending goodness
Seems to still work - https://github.com/LordAro/nml/actions/runs/93337764 - they all failed, but that's just because they don't have permission to upload to PyPI :)
> Rewrite release workflow

- nml/actions/action2var_variables.py
This was overlooked when it was added in PR #84.
> Fix #120: Value range of transported_last_month_pct should be 0..100.

- nml/ast/produce.py
- nml/parser.py
`--nml` output for `produce(...)` was incorrect
> Fix: Produce2 printing

- nml/actions/action2var.py
The range is already checked in `reduce()`
> Fix #121, da57fb5: check StorageOp register range only once

- examples/object/example_object.nml
Returning 0 from tile_check means to disallow placement, and show the
user the first string in the language file. This is not a useful
behaviour, nor a good example for grf authors.
Allowing placement makes more sense!
> Fix: Enable the example object to be placed in-game

- .github/workflows/regression.yml
Not on macOS or Windows, because installing Pillow doesn't work.
Prebuilt wheels for the correct PyPy version aren't [always?] available,
and GitHub's macOS/Windows runners don't have zlib installed so it
can't be built locally.
> Add: [Actions] Include pypy3 on Ubuntu for regression tests.

- nml/actions/action2layout.py
- nml/actions/action2var.py
- nml/expression/functioncall.py
- nml/expression/identifier.py
- nml/global_constants.py
This avoids a lot of nonsense with reverse_lookup().
> Codechange: Make id_list callbacks take a 'name' argument

- nml/actions/action0.py
- nml/actions/action0properties.py
- nml/actions/action2var.py
- nml/actions/action2var_variables.py
- nml/ast/produce.py
- nml/parser.py
This allows to compile FIRS master branch with many warnings.
> Codechange: Reintroduce 0.4 syntax for compatibility

- nml/actions/actionD.py
- nml/expression/identifier.py
- nml/global_constants.py
When a named parameter is defined, it consumes an actionD register, even if it's never accessed later.
This PR solves that by reference counting all identifiers, and assign an actionD register only if it's needed.
The check is not recursive, a named parameter referenced only by an unreferenced one won't be ignored. Same for write only named parameters written multiple times. But I think these cases should not be common.
> Add: Ignore unreferenced named parameters

- nml/actions/action0.py
- nml/actions/action0properties.py
- nml/actions/action2layout.py
- nml/actions/action2random.py
- nml/actions/action2var.py
- nml/actions/action2var_variables.py
- nml/actions/action3.py
- nml/actions/action3_callbacks.py
- nml/actions/actionA.py
- nml/actions/actionD.py
- nml/ast/basecost.py
- nml/ast/snowline.py
- nml/expression/bin_not.py
- nml/expression/binop.py
- nml/expression/bitmask.py
- nml/expression/functioncall.py
- nml/global_constants.py
- nml/nmlop.py
- nml/parser.py
Should be no functional changes, except a few line positions might be tracked implicitly.
Last patch created mostly with some horrible sed expressions.
Regression tests pass.
> Reduce boilerplate for creating BinOps

- nml/ast/switch.py
- nml/expression/array.py
- nml/expression/base_expression.py
- nml/expression/bin_not.py
- nml/expression/binop.py
- nml/expression/bitmask.py
- nml/expression/boolean.py
- nml/expression/spritegroup_ref.py
- nml/expression/storage_op.py
- nml/expression/ternaryop.py
I had the idea after seeing [this pastebin](https://pastebin.com/raw/ECg7qg5L) from Andy.
With this PR the following code
```
switch (FEAT_TRAINS, SELF, open_car_pony_gen_6C_switch_loading_speed_by_cargo_0, cargo_classes & bitmask(CC_PASSENGERS, CC_MAIL, CC_ARMOURED)) {
bitmask(CC_PASSENGERS): return 6;
bitmask(CC_MAIL): return 6;
bitmask(CC_ARMOURED): return 6;
return 6;
}
switch (FEAT_TRAINS, SELF, open_car_pony_gen_6C_switch_loading_speed_by_cargo_1, cargo_classes & bitmask(CC_PASSENGERS, CC_MAIL, CC_ARMOURED)) {
bitmask(CC_PASSENGERS): return 8;
bitmask(CC_MAIL): return 8;
bitmask(CC_ARMOURED): return 8;
return 8;
}
switch (FEAT_TRAINS, SELF, open_car_pony_gen_6C_switch_loading_speed_by_cargo_2, cargo_classes & bitmask(CC_PASSENGERS, CC_MAIL, CC_ARMOURED)) {
bitmask(CC_PASSENGERS): …
```
> Add: optimise switches

- nml/actions/action2.py
- nml/ast/switch.py
- nml/expression/spritegroup_ref.py
Before this rewrite, an optimised switch could output a `returns a constant, optimising` warning at each usage location, and a bogus `is not referenced, ignoring` warning. Now only one `returns a constant, optimising` happens.
There was also an bug in `is_read_only`.
> Switches optimisations improvements and fixes

- nml/actions/action2var_variables.py
- nml/expression/functioncall.py
Yay, more random cleanups.
Slightly RFC on the decorator bit; if this style makes sense there are probably more things to apply it to. Personally I think anything is better than these big tables.
> Builtin functions refactoring

- nml/global_constants.py
OpenTTD/OpenTTD#8392 renames two StringIDs so they more closely match their brethren constants for quantity and abbrevations. This PR adds the missing constants to `global_constants.py`. 
The 'old' constant names are kept, with their original StringID, this way old code depending on these names should not fail.
> Add constants introduced in OpenTTD/OpenTTD#8392.

- README.md
Credits were (very) outdated.  
Credits are easier found via Github contributors listing, no benefit to manually maintaining them.
Section removed.  Link to section removed from table of contents.
> Doc: remove credits section from README

- setup.py
A [change](https://github.com/python-pillow/Pillow/commit/2f409261eb1228e166868f8f0b5da5cda52e55bf) in Pillow 8.1.0 (release 4 days ago) triggers `OSError: buffer overrun when reading image file` for opengfx_generic_trams1.pcx (371x150) and `OSError: image file is truncated (0 bytes not processed)` for opengfx_trains_start.pcx (409x210)
I don't really know if it's a bug in Pillow, but I fixed the issue by croping first file to 370x150 and second file to 408x210.
> Fix: regression failure with Pillow 8.1.0

- nml/actions/action2var_variables.py
- nml/actions/action5.py
- nml/expression/functioncall.py
- nml/global_constants.py
Adds support for some recent NewGRF additions, those that I know what they do.
I am a bit worried about adding such a generic name like "inflation" to the global namespace. But I have no better idea either.
> Add support for recent NewGRF additions

- nml/expression/storage_op.py
We use this range for internal calculations, so user code could get its
values overwritten by ours or vice versa.
Of course this won't catch dynamically-calculated addresses.
> Change: Check that user code doesn't try to use reserved registers

- nml/global_constants.py
This PR adds two new ground sprite constants for "partially cleared" tiles, eg the ones that will gradually appear with more grass over time after bulldozing a tile to the fully cleared state.
I wanted to reuse these tiles for a "swamp" setting that I'm building, and figured it was more of an oversight than a feature that they were not part of the constants. Correct me if I'm wrong!
> Add: Ground sprite constants for  partially cleared tiles

- nml/expression/functioncall.py
Added sqrt function to builtin ones as it could be usefull in other projects.
I implemented it because the SQRT approximation in 2cc_TrainsInNML.grf was giving sometimes weird results. Using math.sqrt is much more accurate.
> Add: support of square root and round functions to builtin functions

- nml/global_constants.py
The name of the constant is the opposite of its meaning, so it needs a rename.
Some constants were already renamed before, and kept for compatibility without users being notified of the deprecation, so I added a way to warn users before adding this new rename.
Fixes #201
> Fix #201: rename MAP_TYPE_RECTANGULAR to MAP_TYPE_SQUARE

- nml/main.py
As suggested in #194, this replaces `Reading ...` message with `Reading filename.nml ...` or `Reading standard input ...` depending on whether an input filename was given.
Closes #194.
> Change: Display input filename

- nml/ast/switch.py
`self.optimised` is used as a replacement in the caller, but for complex expressions a return action is then created when parsing caller's results and this return action uses caller's scope instead callee's one, that was the first bug (fixed with https://github.com/OpenTTD/nml/commit/597685d67869554a5dd6e390ca2be72c78448ecf).
So instead, now the original callee is rewritten like the return action (but with the correct scope) and `string()` was catch in the rewrite, causing their special handling as result values to be ignored.
`string()` return values are similar to numeric constant, they don't trigger the creation of a return action. So there's no need to rewrite switches for them.
> Fix #204: Consider string() as numeric constant when optimising switches

- nml/actions/action2var_variables.py
`town_euclidean_dist` (object var 46, industry var 66) was not following the same pattern as `town_manhattan_dist` (object var 45, industry var 65) while the format of these 4 variables is the same.
> Fix #206: Apply correct mask to `town_euclidean_dist` variables

- nml/lz77.py
`array.array.tostring()` has been renamed to `array.array.tobytes()` in python 3.2, and removed in python 3.9
> Fix: LZ77 fallback is not compatible with python 3.9

- nml/grfstrings.py
- regression/lang/dutch.lng
- regression/lang/english.lng
- regression/lang/us.lng
Recently some language definitions in OpenTTD changed.
* There is a new plural form 14.
* Romanian switched plural forms.
* New languages were added.
This PR adapts NML for that:
* The new plural form is added.
* NML maintained its own list of language ids and plural forms.
* This list is removed.
* NML allowed using an iso-code as ##grflangid. This was undocumented, and probably only used in the regression tests. **This features is removed.**
* NML validated the plural forms of translations against an internal list of all known languages. It errored hard, if they differed. I have no idea why this validation was added. But it is unnecessary, and rejecting old NewGRF sources because some language switched plural forms, is unreasonable. **Thus, this validation is removed.**
In theory, the …
> Clean up language definitions

- nml/actions/action2var_variables.py
Per the comment at https://newgrf-specs.tt-wiki.net/wiki/NML:Deprecated_syntax
Rather than relying on ``var[0x41, 0, 0xFFFF]``, this PR adds a var ``town_index``
Town var 0x41 is a word, at least for OpenTTD purposes: https://newgrf-specs.tt-wiki.net/wiki/VariationalAction2/Towns
Tested with some FIRS code which is not helpful to other people as it has a bunch of unrelated changes, but the var works as expected.
> Add: town var 0x41 'town_index'

- nml/ast/produce.py
Another bug found by @andythenorth :)
Procedure calls in produce blocks were not properly referenced.
> Fix: Procedure calls reference counting

- nml/actions/action2var.py
Errors without the corresponding line number are not very useful.
`action2var.parse_variable()` uses position of number or register when reporting an error, but they usually are not set. So it's better to use the position of the expression itself.
> Fix: Use a most likely defined position when reporting error

- nml/_lz77.c
On newer versions of Python (3.10+) throw the following error:
Error:    (SystemError) "PY_SSIZE_T_CLEAN macro must be defined for '#' formats".
This commit fixes this by defining the PY_SSIZE_T_CLEAN macro as
recommended in the [Python
docs](https://docs.python.org/3/c-api/arg.html#strings-and-buffers).
Signed-off-by: Felix Kaechele <felix@kaechele.ca>
First reported in Fedora here: https://bugzilla.redhat.com/show_bug.cgi?id=1987779
> Fix: define PY_SSIZE_T_CLEAN in _lz77.c

- nml/actions/action0properties.py
- nml/actions/action3_callbacks.py
Depends on https://github.com/OpenTTD/OpenTTD/pull/9346
> Feature: Support for rail vehicle property 0x2E, curve_speed_mod

- docs/changelog.txt
A new release is needed to suppress a warning when building OpenGFX.
> Update: changelog for 0.6.1

- nml/actions/action2var.py
@andythenorth found a bug ;)
```
switch(FEAT_INDUSTRIES, SELF, test_empty_expression_switch,
// NML was throwing a not-descriptive parse error with an empty expression
[]) {
return;
}
```
triggers "IndexError: pop from empty list" at https://github.com/OpenTTD/nml/blob/840613eb393eface5026dd15e491051176f6dc3c/nml/actions/action2var.py#L639.
But it really should have been rejected way earlier.
> Fix: Reject empty arrays of expressions

- .github/workflows/regression.yml
- .github/workflows/release.yml
- .github/workflows/testing.yml
`macos-latest` image is now `macos-11` and doesn't have python 3.5 nor 3.6.
And on January 24th, python 3.5 will be removed from all images.
So I think it's safe to just remove 3.5 and 3.6, and also add 3.9 and 3.10 in the checks.
Also update workflows to use `windows-latest` image as `windows-2016` is deprecated
> Update: [Actions] python versions for regression test

- nml/expression/base_expression.py
Black 22.1.0 now removes spaces around power operators if both operands are simple.
> Codechange: black changed code style for power operators

- nml/actions/action2layout.py
When testing stations, an issue was discovered for advanced sprite layouts.
If there's no buildingsprite, nmlc uses basic format "no building" output, but that's incorrect for advanced format.
As OpenTTD ignores this invalid data because it never supported basic format and just loops over `num-sprites` it was working fine (except for stations because prop 1A can define more than one layout, and invalid data is read in this case).
So nmlc had to be fixed with 2 options, rejecting no building for advanced sprite layouts, or allow no building and fix the output (requiring an update of the spec). 
We decided to update the spec to explicitely allow no building for advanced sprite layout as it was already supported by OpenTTD.
This PR implements the modified spec, and fixes the invalid output.
> Fix: advanced spritelayout may use no buildings

- nml/actions/action2var.py
- nml/actions/actionD.py
- nml/expression/__init__.py
- nml/expression/abs_op.py
- nml/expression/functioncall.py
This avoids the function argument being replicated in the output and being executed at run-time three times.
> Fix #253: Use non-ternary varaction2 sequence for abs() builtin function

- nml/ast/switch.py
> Fix: missing int > scope conversion for random_action with vehicle-offset

- nml/expression/abs_op.py
- nml/expression/bin_not.py
- nml/expression/bitmask.py
- nml/expression/boolean.py
- nml/expression/storage_op.py
- nml/expression/ternaryop.py
- nml/generic.py
- nml/nmlop.py
Error messages like `Binary operator requires both operands to be integers or floats.` are not very understandable for users when the error is simply a missing `()`.
Added special handling for these errors so users will get a more useful `Missing '()' after '<procedure_name>'.` message.
I think I found all possible occurrences.
> Codechange: improve error reporting for procedure calls missing '()'

- nml/editors/visualstudiocode.py
For the VSCode extension I provide suggestions, however, for this I require a list of all keywords. This was previously hardcoded but I think it's best if this is also generated through the generator. I periodically let a [Actions script](https://github.com/spnda/VSC-NML/blob/master/.github/workflows/syntax_update.yml) generate these JSONs to keep the extension updated. Would be nice if this could get merged asap :)
> Change: Export keyword JSON for VSCode

- nml/actions/action2var_variables.py
Station variable `nearby_tile_platform_type` has a weird name and weird value range 0-3, compared to the other `tile_type` variables and callbacks with range 0-7.
This renames the variable and changes the value range to fit with the rest.
* name: `nearby_tile_tile_type`
* range 0-8
* the orientation bit is relative to the querying tile's orientation, but that can be explained in the docs.
> Change: replace nearby_tile_platform_type with nearby_tile_tile_type.

- nml/global_constants.py
The synchronized-tile-trigger is called from the station-acceptance-update cycle, not from the tile loop.
> Fix: Station animation triggers every 250 ticks, not 256.

- .github/workflows/commit-checker.yml
- .github/workflows/regression.yml
- .github/workflows/release.yml
- .github/workflows/testing.yml
- docs/changelog.txt
While writing documentation for stations, we made some small changes to the syntax.
Let's release a version matching the documentation.
> Update: changelog for 0.7.1

- .github/workflows/release.yml
Bumping versions in workflows changed the path where manylinux puts generated wheels.
> Fix: [Actions] release workflow issues

- .github/workflows/release.yml
Adding `--verbose` to pip command helped to find the manylinux issue, keeping it will not hurt :)
Manylinux issue was
```
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
Git checkout found but cannot determine its version. Error:  Command '['git', '-C', '/github/workspace', 'diff-index', 'HEAD']' returned non-zero exit status 128.
```
So no surprised it decided to use 0.0.0 as version.
While fixing stuff `set-output` is deprecated.
Will also need to replace `actions/upload-release-asset` as …
> More issues in release workflow

- nml/actions/action0properties.py
- nml/global_constants.py
This is draft, the patch is simple, but I'm not convinced `variant_group` is the best name for the action 0 prop.
Supports Peter's addition of vehicle variants in client.
> Feature: support for variant_group action 0 prop for vehicles

- nml/global_constants.py
To define ELRL trains, you can either
* define a railtype table containing ELRL, or
* use track_type=RAIL with engine_class=ENGINE_CLASS_ELECTRIC.
This was already reflected in the documentation.
In no case does ELRL match MONO.
> Fix: By default there is no ELRL railtype.

- nml/actions/action2random.py
- nml/actions/action2var_variables.py
The top 8 bits will always be zero if the game does not support 16 bit vehicle. random data.
OpenTTD#10701 increased vehicle random bits from 8 to 16. This change does the NML side.
Not tested.
> Change: Extend vehicle random bits to 16.

- nml/actions/action0.py
- nml/actions/action3.py
Draft, support for https://github.com/OpenTTD/OpenTTD/pull/10672
> Support extended object/station/roadstop limits (draft)

- .github/workflows/release.yml
Release workflow needed some work (again).
Removed actions/upload-release-asset as it's very outdated.
Use GitHub CLI to upload the assets.
I tested it on https://github.com/glx22/nml/releases/tag/0.7.2 ([workflow run](https://github.com/glx22/nml/actions/runs/4726187062) with wheels publishing disabled)
> Codechange: [Actions] Use 'gh' to upload release assets

- nml/global_constants.py
Would be used instead of 0xFF with properties: draw_pylon_tiles, hide_wire_tiles and non_traversable_tiles.
> Add: STAT_ALL_TILES constant for use instead of 0xFF 

- .github/workflows/regression.yml
Regression log is very noisy with each test triggering
```
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
Git checkout found but cannot determine its version. Error:  Command '['git', '-C', '/Users/runner/work/nml/nml', 'describe', '--tags', '--long']' returned non-zero exit status 128.
Git checkout found but cannot determine its version. Error:  Command '['git', '-C', '/Users/runner/work/nml/nml', 'describe', '--tags', '--long']' returned non-zero exit status 128.
```
Fetch more data during checkout so `git describe` can do its job.
> Fix: [Actions] nmlc version could not be determined during regression

- nml/grfstrings.py
Nml implementation for https://github.com/OpenTTD/OpenTTD/pull/10782
> Add: Support for {FORCE} string command

- nml/ast/alt_sprites.py
- nml/main.py
Following a discord conversation.
* zephyris
Hey, nmlc question for you all. Is there an argument which makes it ignore alternate zoom sprites? Similarly, make it ignore 32bpp alternates of sprites?
* zephyris
I'm hoping to make multiple versions of a grf at build time - file sizes get pretty enormous when including 32bpp and not everyone will need/want that.
* glx
I think it should be possible to add nozoom and no32bpp flags to nmlc
And it is indeed possible :)
> Add: --no-32bpp and --no-extra-zoom option to skip some alternative sprites

- docs/changelog.txt
Hoping nothing broke in the release workflow in 1 week.
> Update: changelog for 0.7.3

- nml/actions/action5.py
Fixes #290.
Currently there are 3 `replacenew`-types to replace signal graphics:
* `PRE_SIGNAL`
* `PRE_SIGNAL_SEMAPHORE`
* `PRE_SIGNAL_SEMAPHORE_PBS`
They all create the same code.
Add a new type `SIGNALS`, not to be confused with the existing `NEW_SIGNALS`.
The 3 old types will be deprecated and removed from the documentation.
> Change: Use a single replacenew-type 'SIGNALS' instead of 3 different constants.

- nml/ast/switch.py
From a stacktrace reported on discord:
```
Preprocessing ...Traceback (most recent call last):
File "nmlc", line 6, in <module>
File "nml\main.py", line 623, in run
File "nml\main.py", line 339, in main
File "nml\main.py", line 439, in nml
File "nml\ast\base_statement.py", line 155, in pre_process
File "nml\ast\item.py", line 99, in pre_process
File "nml\ast\base_statement.py", line 155, in pre_process
File "nml\ast\item.py", line 236, in pre_process
File "nml\ast\item.py", line 295, in reduce_expressions
File "nml\actions\action2var.py", line 1156, in reduce_varaction2_expr
File "nml\expression\identifier.py", line 74, in reduce
File "nml\expression\spritegroup_ref.py", line 85, in reduce
File "nml\ast\switch.py", line 96, in optimise
File "nml\expression\spritegroup_ref.py", line 98, in …
```
> Fix dfb4499: incomplete read only checks (again)

- nml/global_constants.py
Following addition of newgrf roadstops, these are useful constants.
> Change: add constants GROUNDSPRITE_ROAD_X and GROUNDSPRITE_ROAD_Y

- nml/actions/action3_callbacks.py
Implement support for OpenTTD's "vehicle build probability" callback 162.
This was intended to be a generic probability action, with the action provided in var 10. This is handled by nmlc.
The callback is implemented as 'reverse_build_probability`.
> Add: Support for build probability action CB 162 var10 0 (reverse rail vehicle)

- nml/actions/action0properties.py
Add support for the new ship Action0 properties from OTTD#10734. Add support for 0x24 byte for ship acceleration and 0x23 word for ship speed, the latter only set if speed is >255 thus does not fit in the existing 0x0B byte for ship speed.
(This seems to work as expected, but is my first time trying to update nml - I may well have made mistakes/be wrong!)
> Add: Support for faster ship speed 23 and acceleration 24 (OTTD #10734)

- nml/actions/action0properties.py
- nml/global_constants.py
Provides support for town production effect and multiplier properties of OpenTTD#11947
```
town_production_effect:     TOWNPRODUCTION_PASSENGERS;
town_production_multiplier: 1.0;
```
```
town_production_effect:     TOWNPRODUCTION_MAIL;
town_production_multiplier: 0.75;
```
> Add: Support town_production_effect and town_production_multiplier.

- nml/main.py
To defend authors against mixing Windows / DOS palettes in the same grf, nmlc will open all sprite files from the filesystem and validate their palette. This is a separate step to sprite encoding.
For certain cases, this is of no benefit, and just increases compile times. For example, with Iron Horse:
* sprites are generated via a separate PIL compile step prior to nmlc
* the DOS palette is set during that sprite generation step as a necessary part of creating paletted image files
* therefore the subsequent nmlc check is redundant
The nmlc palette check adds 1s to 2s to every Iron Horse compile for me, which is 5% to 10% of total compile time.
I previously tried to solve this in #254, by inferring when the sprites might not need processed, but that route was not viable, as it depended too …
> Change: add --no-palette-validation optional arg

- docs/changelog.txt
And this time I'll trigger a release immediately after the merge.
> Update: changelog for 0.7.5

- .github/workflows/regression.yml
`macos-latest` doesn't have python 3.7 or 3.8 (though regression in PRs fails only for missing 3.7).
Test with more recent python version for all targets.
> Update: Python versions for regression

- nml/actions/action2var_variables.py
This was a joint variable for random_bits_tile and random_bits_station, it is not required, and not in the list of documented variables.
> Change: Remove road stops variable random_bits

- nml/actions/action3_callbacks.py
`availability` callback is not marked as being a purchase callback so it's not properly registered in action3.
Fix the issue.
> Fix #337: Station 'availability' is a purchase callback

- nml/actions/action2var_variables.py
Since OpenTTD#12890, 8 bits of station tile type are returned in var 40.
This PR support this change in NML.
> Change: Support for 8 bit station tile types.

- nml/ast/replace.py
`replace()` can only be used for TTD sprites (0-4895), or with return value of `reserve_sprites()`.
> Add: Basic range check for replace()

- nml/tokens.py
Whitespace handling in parser doesn't use raw string for the token rule, but it should have.
It somehow works when not using raw string with python <3.13, but fails with python 3.13.
Use raw strings for all token regular expressions.
> Fix #340: Always use raw strings for token regex

- nml/grfstrings.py
- nml/main.py
When you have a huge language file it's easy to end up with useless strings when modifying grf source.
The translators then have to translate useless strings.
Add an nmlc option to list unused strings.
> Add: --list-unused-strings to list the unused strings

- nml/actions/action5.py
To support base graphics set road waypoints, [type `19`](https://newgrf-specs.tt-wiki.net/wiki/Action5#type) was added to Action5. This is for setting the 4 base road waypoint sprites.
This PR adds a new `ROAD_WAYPOINTS` type for `replacenew` to support this feature in nml.
> Add: Support for Action5 type 19 road waypoints

- .github/workflows/regression.yml
`PyPy` needs `libjpeg-dev` to build `Pillow`.
`ubuntu-22.04` comes with `libjpeg-dev` preinstalled.
`ubuntu-24.04` doesn't come with `libjpeg-dev` preinstalled.
`ubuntu-latest` is transitioning from `ubuntu-22.04` to `ubuntu-24.04`.
Install `libjpeg-dev` manually for PyPy.
> Fix: [Actions] Install missing deps for PyPy

- nml/actions/action2var.py
If a switch has more than 255 ranges, nmlc will trigger [this assert](https://github.com/OpenTTD/nml/blob/master/nml/output_base.py#L146).
Check earlier to report the error to the user in a more useful way.
> Fix: Properly check number of varaction2 ranges

- nml/actions/action2var_variables.py
Though roadstop variables `0x43` and `0x44` could range from `0` to `0xffffffff`, only the first eight bits are actually used.
This PR fixes this problem.
> Fix: incorrect start values for roadstop var 43/44

- nml/actions/action0.py
- nml/expression/string_literal.py
Length check for string literal properties is dumb, it uses `len()` so `len('NML_')` is 4 and `len('\FFNML')` is 6.
Use `grfstrings.get_string_size()` so the length checks are done on actual length in bytes.
> Fix #354: Improve length check for string literal properties

- nml/expression/base_expression.py
Fixes #238, which refers to the error message in Action2 parser not containing `produce-block` as a relevant block.
This is my first commit to this repository, I hope someone will guide me in case anything is not correctly presented.
> Fix: Include information about relevant block in ScriptError message

- nml/actions/action0properties.py
- nml/actions/action3_callbacks.py
See https://github.com/OpenTTD/OpenTTD/pull/13090
> Change: add vehicle 'refit' callback (cb 0x163) and cargo class filter prop (0x28 for trains etc)

- nml/grfstrings.py
`black-25` doesn't not do the same as `black-24`.
> Codefix: There's a new version of 'black'

- .github/workflows/regression.yml
- nml/actions/real_sprite.py
- nml/main.py
- pyproject.toml
When installing using `pip install nml`, if there's no wheel for a given python-os-arch it has to be built from source.
As build is done in isolated environment it fails with:
```
Processing /home/runner/work/nml/nml
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'done'
Collecting Pillow>=3.4 (from nml==0.0.0)
Using cached pillow-11.1.0-cp39-cp39-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting ply (from nml==0.0.0)
Using cached ply-3.11-py2.py3-none-any.whl.metadata (844 bytes)
Using cached …
```
> Fix: 'pip install nml' fails to build from source

- .github/workflows/release.yml
Old release workflow use [RalfG/python-wheels-manylinux-build](https://github.com/RalfG/python-wheels-manylinux-build) to build wheels for linux, and `python setup.py [sdist] bdist_wheel` for macos and windows.
[RalfG/python-wheels-manylinux-build](https://github.com/RalfG/python-wheels-manylinux-build) is archived in favour of [PyPA/cibuildwheel](https://github.com/pypa/cibuildwheel).
There's a lot of copy/paste between the different jobs.
The new workflow using [PyPA/cibuildwheel](https://github.com/pypa/cibuildwheel) can build wheels for many combinations of OS and python versions:
- 40 linux wheels (i686, x86_64, manylinux) for python 3.6 to 3.13 and pypy 3.7-3.10
- 20 linux-arm wheels for python 3.6 to 3.13 and pypy 3.7-3.10
- 20 windows wheels (win32 and win_amd64) for python 3.6 to …
> Change: [Actions] Use cibuildwheel for releases

- docs/changelog.txt
I think I properly classified the commits.
I also checked release workflow still work (in my fork).
> Update: changelog for 0.7.6

- nml/actions/action5.py
To support snowy rocks, type 1A was added to Action5. This is for setting the 5 sets of 19 (normal, 1/4 snowy, 2/4 snowy, 3/4 snowy and 4/4 snowy) base rock overlay sprites.
This PR adds a new OVERLAY_ROCKS type for replacenew to support this feature in nml.
> Add: Support for Action5 type 1A overlay rocks

- nml/global_constants.py
The wildcards `ALL_NORMAL_CARGO_CLASSES` and `ALL_CARGO_CLASSES` were not updated when `CC_POTABLE` and `CC_NON_POTABLE` were added.
> Fix: ALL_NORMAL_CARGO_CLASSES and ALL_CARGO_CLASSES did not include newer cargo classes.

- nml/actions/action2var.py
Stations usage of SpriteLayouts is very different to other features, but it may happen an author write a switch returning a SpriteLayout (like it's done for other features).
This triggers [this assert](https://github.com/OpenTTD/nml/blob/master/nml/actions/action2.py#L462), which is not helpful for the author.
A [check exist](https://github.com/OpenTTD/nml/blob/master/nml/actions/action2layout.py#L537-L540) to prevent invalid use of SpriteLayout when following 1/2/3, but stations are allowed to have SpriteLayout with a special handling.
Detect the problem before asserting and output a more useful error message.
Doing the same kind of check for SpriteGroup is not necessary here because it's already handled [here](https://github.com/OpenTTD/nml/blob/master/nml/actions/action2real.py#L47-L53) …
> Fix: Nicer error message when a station switch returns a SpriteLayout

- .github/workflows/release.yml
I completely forgot `gh` required a git repository when rewritting the release workflow, luckily it failed after uploading to pypi, so I could manually attach the source package to the github release.
I had different options to fix the issue:
- Insert the following block before `gh` command
```
git init
git remote add origin ${{ github.event.repository.html_url }}
```
- Move the `gh` command to `build_sdist` job, with the advantage of quicker availability of the source package on github release.
I chose to move the command.
> Fix 530e325f: 'gh' requires a git repository

- nml/actions/action0.py
https://github.com/OpenTTD/OpenTTD/pull/12288 increased House limit per newgrf to 4096, but nml was not updated. (BTW old value was off by one).
I also noticed an off by one error for Industry Tile (255 per newgrf).
> Fix #367: Incorrect limits for House and Industry Tile

- nml/actions/action1.py
- nml/ast/grf.py
Flake8 7.2.0 introduced new checks and in result we get
```
Error: nml/actions/action1.py:191:5: F824 `global spriteset_collections` is unused: name is never assigned in scope
Error: nml/ast/grf.py:141:9: F824 `global param_stats` is unused: name is never assigned in scope
```
After some reading, these two `global` are not needed because we modify the actual object and not the reference to the object.
So make flake8 happy again and remove the useless `global`.
> Codefix: Remove unneeded "global"

- nml/global_constants.py
* There are two new animation triggers for stations and roadstops since OpenTTD/OpenTTD#14080.
* Stations used a different naming pattern for animation triggers than other features, so add new constants.
* Add missing roadstop random triggers.
> Add: Constants for (new) station and roadstop animation and random triggers.

- nml/actions/action5.py
Addition of the new badge menu vertical ellipsis icon increases the valid range for `OTTD_GUI`. Update `action5.py` to match this range.
> Add: Support for badge menu vertical ellipsis icon

- docs/changelog.txt
Major change with dependencies deserves a major upgrade (I think).
Also building OpenGFX2 requires some changes introduced after 0.7.6 so a new release is necessary.
As always I checked the workflows on my fork (except upload step of course).
> Update: changelog for 0.8.0

- .github/workflows/testing.yml
- Makefile
- pyproject.toml
`black` supports storing configuration in `pyproject.toml`. This pull request moves the existing command-line options to the file.
I think this change has a few advantages:
* The current command-line options are duplicated in two places (Makefile and Github Actions), the `pyproject.toml` is a unified place.
* By putting the configuration in `pyproject.toml`, running `black .` anywhere within the repository would produce correct results. This guards against a lot of surprises.
* Caveat: running `black <a file name that's excluded>` still formats what should not be formatted. This is a special case that's no worse than before though.
I also included `setup.py` in the excludes just in case people run `black .` instead of `black nml` in the repository root.
> Change: move `black` options to `pyproject.toml`
