OpenTTD/nml

gen_editor, nml/editors/visualstudio.py
Added the Script for creating a Visual Studio .json Highlighting File.
Also Changed up the gen_editor file to give a response on creating a file.
gen_editor now has 2 commands for creating the Visual Studio Script. [visualstudio, vs]
=> Added Visual Studio Editor Script

.gitignore
There might be some other things from .hgignore to add to .gitignore, but this is the only one that has come up for me so far.
=> Codechange: add nmlcache to .gitignore

.devzone/build/jenkins_build.sh, .devzone/build/jenkins_postbuild.sh
Some small improvements to the build scripts
=> Devzone fixes

README.md
=> Fix 014febc: wrong link to LICENSE file

nml/grfstrings.py
Add support for PUSH/POP_COLOUR codes, as in https://github.com/OpenTTD/OpenTTD/pull/7527
=> Add: PUSH/POP_COLOUR codes.

nml/actions/action5.py
The number of GUI sprites has increased according to NRT (OpenTTD/OpenTTD#6811).
=> Fix: Update OTTD_GUI sprite count.

nml/ast/cargotable.py
=> Fix #40: issue a warning on duplicate CTT entries

.github/workflows/regression.yml
Output will look like in https://github.com/glx22/nml/pull/1
=> Add: regression workflow for PR and push to master

nml/expression/storage_op.py
Following OpenTTD https://github.com/OpenTTD/OpenTTD/pull/6885
Untested other than running regression tests. Afaict it's just a limit.
Might then want to update https://newgrf-specs.tt-wiki.net/wiki/NML:Builtin_functions
=> Change: increase size of permanent storage to 256

nml/global_constants.py
Follows https://github.com/OpenTTD/OpenTTD/pull/7182
Untested, except that regression tests pass.
Would also want nml wiki updated: https://newgrf-specs.tt-wiki.net/wiki/NML:Airports
=> Change: add ANIM_TRIGGER_APT_AIRPLANE_LANDS

nml/actions/action2var_variables.py
=> Add: Station var 0x6A nearby_tile_grfid

setup.py
As per @matthijskooijman 's issue.
=> Fix #58: Loosen Pillow version constraint

README.md
=> Readme release instructions

README.md
Incorporates learnings from 0.5.0 release.
=> Doc: more acccurate release process in README

nml/expression/functioncall.py
This only adds to the copy-pasting, but eh.
=> Add: Builtin functions `roadtype()` and `tramtype()`.

nml/actions/action2layout.py
Fixes https://dev.openttdcoop.org/issues/8519
=> Fix: Allow calculation for palette in spritelayout

docs/changelog.txt
Taken straight from the git log, and with extraneous commtis removed. Feel free to correct me.
=> Doc: Changelog for 0.5.1

nml/generic.py, nml/main.py, nml/spritecache.py, nml/spriteencoder.py
=> Fix #139: Make --cache-dir work, and avoid creating dirs with --no-cache

nml/actions/action3_callbacks.py, nml/actions/action7.py, nml/actions/real_sprite.py, nml/generic.py, nml/grfstrings.py, nml/main.py, nml/output_grf.py, nml/parser.py, nml/spriteencoder.py, nml/tokens.py, nml/version_update.py
=> Trying to fix some CodeQL alerts

Makefile, README.md
I don't know how you invoke black. But there are quite some custom options for NML.
=> Add: make target to run black-formatter as it is used in PR checks.

nml/actions/action2layout.py, nml/actions/action2var.py, nml/expression/array.py, nml/expression/base_expression.py, nml/expression/bin_not.py, nml/expression/binop.py, nml/expression/bitmask.py, nml/expression/boolean.py, nml/expression/cargo.py, nml/expression/functioncall.py, nml/expression/functionptr.py, nml/expression/identifier.py, nml/expression/parameter.py, nml/expression/patch_variable.py, nml/expression/special_parameter.py, nml/expression/spritegroup_ref.py, nml/expression/storage_op.py, nml/expression/string.py, nml/expression/string_literal.py, nml/expression/ternaryop.py, nml/expression/variable.py, nml/generic.py
In #155, there was a comment about [list as default argument having issues](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments). So I decided to fix that.
=> Fix: Don't use [] as default arg

nml/actions/action0.py, nml/actions/action0properties.py, nml/actions/action2layout.py, nml/actions/action2production.py, nml/actions/action2random.py, nml/actions/action2var.py, nml/actions/action3.py, nml/actions/action4.py, nml/actions/real_sprite.py, nml/ast/general.py, nml/ast/switch.py, nml/expression/cargo.py, nml/expression/functioncall.py, nml/expression/functionptr.py, nml/grfstrings.py, nml/output_base.py
None of the fixes are critical. But the noise in "make flake" annoys me :)
=> Fix/silence warning from flake8-bugbear.

.github/workflows/testing.yml
We forgot to apply this change here
=> Fix: [Actions] CodeQL can now run on the merge commit

nml/actions/action0.py, nml/actions/action14.py, nml/actions/action2.py, nml/actions/action2real.py, nml/actions/action2var.py, nml/actions/action3.py, nml/actions/action5.py, nml/actions/actionD.py, nml/actions/real_sprite.py, nml/ast/cargotable.py, nml/ast/produce.py, nml/ast/sprite_container.py, nml/ast/switch.py, nml/ast/townnames.py, nml/expression/parameter.py, nml/generic.py, nml/global_constants.py, nml/grfstrings.py, nml/main.py, nml/output_grf.py, nml/spritecache.py, nml/tokens.py
This allows to silence some annoying warnings.
=> Add: Options to disable optimisation and/or deprecation warnings

docs/changelog.txt
Closes #193
I have NFI how to force-push to someone else's PR without rights on their repo, so I made a new one.
=> Update: changelog for 0.6.0

nml/actions/action5.py
This reflects OpenTTD/OpenTTD#9067
=> Update: increase number of OTTD_GUI sprites to 191

nml/global_constants.py
Support for [OpenTTD/OpenTTD#9834](https://github.com/OpenTTD/OpenTTD/pull/9834)
=> Add: Map seed in patch variable 0x17.

docs/changelog.txt
0.7.0 because it includes a "big" feature.
I only included commits directly affecting users, and reworded some of them.
=> Update: changelog for 0.7.0

nml/actions/action0properties.py
0x0C had been replaced with 0x0B and 0x0C with 0x0D
=> Fix action0properties.py

nml/actions/action2var_variables.py
=> Fix #256: Objects have a 'colour' in var 47.

nml/actions/action12.py, nml/actions/action2var.py, nml/grfstrings.py, nml/main.py
PR checks use a newer version of black, which the main branch does not comform to.
Reformat source with black 23.1.
=> Update: reformat source with black 23.1

.github/workflows/testing.yml
TrueBrain/actions-flake8 from master to v2
=> Update: [Actions] Bump used actions versions

nml/actions/action0.py, nml/actions/action0properties.py, nml/actions/action2.py, nml/actions/action2var.py, nml/actions/action2var_variables.py, nml/actions/action3_callbacks.py, nml/ast/general.py, nml/global_constants.py
See: https://github.com/OpenTTD/OpenTTD/pull/10144
=> Add: Road stops (feature 0x14)

docs/changelog.txt
With vehicle variants and road stops, I think it's a good idea to make a release.
This time I ran the release workflow on my fork to be sure it still works.
=> Update: changelog for 0.7.2

docs/changelog.txt
=> Update: changelog for 0.7.4

docs/changelog.txt
There are still some open PRs, but the broken compatibility for station NewGRF needs to be addressed.
=> Update: changelog for 0.7.5

nml/actions/action2var_variables.py, nml/global_constants.py
Add: Constants and varact2 variable associated with road waypoints
See: https://github.com/OpenTTD/OpenTTD/pull/12572
=> Add: Constants and varact2 variable associated with road waypoints

nml/actions/action2var_variables.py, nml/global_constants.py
New variable from OpenTTD/OpenTTD#13934
=> Add: Road/tram/railtype variable 0x45.

nml/actions/action2var_variables.py
=> Add: Parent scope for airports and airport tiles.

nml/editors/extract_tables.py
Add station properties dictionary to the list of properties in editor script
=> Add: station properties to editor symbols script
